### PR TITLE
Fix instance path for the backup, progress and download url.

### PR DESCRIPTION
**Pull request by dzschille**
I created a bug, here is the fix for it. 
When chosen source is "confluence" i had set the INSTANCE var at beginning to a subdirectory. Because of this the cookie creation failed and you got an "authorization failure".

### CODE REVIEW

**Comment by mattock** [comment]
Is it the cookie generation that fails? I'm wondering because I'm using the latest version (HEAD at 8caa05477f660087c1) and my backups still seem to work ok.

**Comment by dzschille** [comment]
Yes, it is. But only in case your are doing a confluence backup. Jira works well, because there is no path (wiki) added.

**Comment by dzschille** [comment]
@mattock do you tried the backup for both, jira and confluence?

**Comment by mattock** [comment]
@dzschille : I backup both JIRA and Confluence.

**Comment by mattock** [comment]
@dzschille I applied your patch on top of my Git repo on my backup server. The next run is scheduled for 29th June. I also removed the authorization cookies just in case. If both JIRA and Confluence backups continue working I'll merge this PR.

**Comment by dzschille** [comment]
@mattock nice that you will try it.
On my server it works well:

```
-rw-r--r-- 1 dzschille users  3990966 21. Mai 06:03 CONFLUENCE-backup-20170521.zip
-rw-r--r-- 1 dzschille users  3811336 28. Mai 06:03 CONFLUENCE-backup-20170528.zip
-rw-r--r-- 1 dzschille users  3912242  4. Jun 06:03 CONFLUENCE-backup-20170604.zip
-rw-r--r-- 1 dzschille users  3893387 11. Jun 06:03 CONFLUENCE-backup-20170611.zip
-rw-r--r-- 1 dzschille users  3925865 18. Jun 06:03 CONFLUENCE-backup-20170618.zip
-rw-r--r-- 1 dzschille users  3903147 25. Jun 06:03 CONFLUENCE-backup-20170625.zip
-rw-r--r-- 1 dzschille users  3912127  4. Jun 15:03 CONFLUENCE-backup.zip
-rw-r--r-- 1 dzschille users 20898141 21. Mai 05:02 JIRA-backup-20170521.zip
-rw-r--r-- 1 dzschille users 20934478 28. Mai 05:02 JIRA-backup-20170528.zip
-rw-r--r-- 1 dzschille users 21053235  4. Jun 05:02 JIRA-backup-20170604.zip
-rw-r--r-- 1 dzschille users 21157953 11. Jun 05:02 JIRA-backup-20170611.zip
-rw-r--r-- 1 dzschille users 21199341 18. Jun 05:02 JIRA-backup-20170618.zip
-rw-r--r-- 1 dzschille users 21921794 25. Jun 05:02 JIRA-backup-20170625.zip
-rw-r--r-- 1 dzschille users 21053700  4. Jun 07:02 JIRA-backup.zip
```

**Comment by mattock** [comment]
@dzschille I've verified that this PR does not break my backups. Merging.

**Pull request merged**
