### PR TITLE
Feature/wiki backup

### PR DESCRIPTION
**Pull request by dzschille**
Now you can call the script with arguments. Useful when you running it with more than one cronjobs, like one for a Jira backup and one for a Confluence.

Usage:
`    backup.sh --attachments true --timestamp true --source confluence`

For more details, see README.md

### CODE REVIEW

**Comment by dzschille** [comment]
Oh no, you have added the same features at the same day in 40fddeddc27 ! :-)
So i just close this. 
Good work!

**Comment by mattock** [comment]
@dzschille could you issue a second PR which implements SLEEP_SECONDS and --attachments? Those are useful features imho.

**Comment by dzschille** [comment]
@mattock okay, i will make a second PR. Is it okay, that i implement the --source argument also? It makes it easier to handle multiple arguments, when they all have a name. So i would like to end up with this usage:
`backup.sh --attachments true --timestamp true --source confluence`

In the moment i have implemented --source to work with the parameters "jira", "wiki" and "confluence". "jira" is default.

**Comment by mattock** [comment]
@dzschille yes, feel free to improve parameter handling in the way you described. For my simplistic needs just taking the first parameter as the "source" was good enough.

**Pull request closed without merging**
